# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='converter.Variable'),
        ),
        migrations.AddField(
            model_name='data',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='converter.Year'),
        ),
    ]
