# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdf')),
                ('csv', models.FileField(default=None, null=True, upload_to='csv')),
            ],
        ),
    ]
