# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='variable',
            field=models.CharField(max_length=256),
        ),
        migrations.DeleteModel(
            name='Variable',
        ),
    ]
