# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_auto_20170414_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='amount',
            field=models.CharField(max_length=256),
        ),
    ]
